base_model: "unsloth/Llama-3.2-3B-Instruct" # or choose "unsloth/Llama-3.2-1B-Instruct"
pretrain_model: "../../lora_models/sft/Llama-3.2-3B-Instruct"
data_path: "hungsvdut2k2/vietnamese-chat-doctor"
chat_template: "llama-3.1"